### ISSUE TITLE
[Request] Any chance to incorporate Item Price Helper?

### ISSUE THREAD

**Issue by ToMattBan** [Faeryn/OutwardBetterInventory#2]
Not really an issue, more a request.

Is there any chance to incorporate the mod Item Price Helper (https://outward.thunderstore.io/package/Gurrnak/Item_Price_Helper/) in this one?

The original mod don't work well anymore and conflict with your, like the another issue here showed, but it is really useful. Also, I believe that it fits right in your mod, because it make the inventory better XD.

Thank you man.

**Comment by EremesNG** [comment]
I came to ask the same, would be awesome.

**Comment by Faeryn** [comment]
Do you want all its features or just the item price display?

**Comment by Faeryn** [comment]
I added an item base price display for now. Originally I was hesitant to add this feature because BetterInventory was supposed to be a QoL only mod (aka no "cheaty" features) and I was planning to implement the item price checking in a more immersive way - something like "appraise" skill, that you can learn from a NPC.
This'll work for now, since I'm not actively modding right now.

**Comment by ToMattBan** [comment]
@Faeryn maybe you can put a "On/Off" in the settings of the mod, then it will still be focused on QoL but the user can switch this "cheat" on. 
Just if you have time, of course, I would do if I know how hahaha

**Comment by Faeryn** [comment]
It has on/off, in fact I just set it to default on

**Comment by Faeryn** [comment]
Closing this as I added the feature (with some extras).
